### ISSUE TITLE
Can we fix this issue with Mongoose

### ISSUE THREAD

**Issue by maksymseleznov** [jbdemonte/mongoose-elasticsearch-xp#8]
DeprecationWarning: Mongoose: Query.prototype.stream() is deprecated in mongoose >= 4.5.0, use Query.prototype.cursor() instead

**Comment by jbdemonte** [comment]
Sorry for the delay, I'm working on it, but It seems I'm facing to a bug:
https://github.com/Automattic/mongoose/issues/4998

**Comment by jbdemonte** [comment]
I guess I'm going to wait 1 or 2 month before updating to the cursor, to wait the update to be dry :)

**Comment by hoangnguyenasnet** [comment]
I'm facing the same issue, any update for it?

**Comment by jaydub2099** [comment]
I was looking into this issue locally and have running code using cursor() in place of stream() with success so far. Note however that cursor() was added in mongoose 4.5.0 and this project lists mongoose version minimum of 4.2.2 which would presumably fail if calling cursor() instead of stream().

**Comment by jbdemonte** [comment]
I guess now, it will be far enough to be updated :)

**Comment by nodkz** [comment]
Fixed in #38 with mongoose 5.0.0

**Comment by jaydub2099** [comment]
You bumped the module dependencies but you didn't bump the version of this module itself. Given that the change to mongoose 5.x is a pretty large jump from the previous dep of 4.2.x you should make that change be reflected in a new release of this module.

I know that for various reasons my org cannot jump from our current production version of mongoose to 5.x right now but if someone wants to npm install this module at current version 5.2.0 they are going to get a different module dep for mongoose than I have locally since I npm installed 5.2.0 a few weeks back with the old mongoose deps...
